name: Build memedit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Compile memedit
        run: arm-linux-gnueabihf-gcc -static -o memedit memedit.c

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: memedit
          path: memedit
